/*
 * Selling Partner API for Orders
 * The Selling Partner API for Orders helps you programmatically retrieve order information. These APIs let you develop fast, flexible, custom applications in areas like order synchronization, order research, and demand-based decision support tools.
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.amazon.spapi.model.orders_api_model;

import java.util.Objects;
import java.util.Arrays;
import com.amazon.spapi.model.orders_api_model.ItemApprovalAction;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Order item apecific approval request.
 */
@ApiModel(description = "Order item apecific approval request.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-05-03T21:37:44.667-04:00")
public class OrderItemApprovalRequest {
  @SerializedName("OrderItemId")
  private String orderItemId = null;

  @SerializedName("ApprovalAction")
  private ItemApprovalAction approvalAction = null;

  public OrderItemApprovalRequest orderItemId(String orderItemId) {
    this.orderItemId = orderItemId;
    return this;
  }

   /**
   * The unique identifier of the order item.
   * @return orderItemId
  **/
  @ApiModelProperty(required = true, value = "The unique identifier of the order item.")
  public String getOrderItemId() {
    return orderItemId;
  }

  public void setOrderItemId(String orderItemId) {
    this.orderItemId = orderItemId;
  }

  public OrderItemApprovalRequest approvalAction(ItemApprovalAction approvalAction) {
    this.approvalAction = approvalAction;
    return this;
  }

   /**
   * Approval action that defines the behavior of the ItemApproval.
   * @return approvalAction
  **/
  @ApiModelProperty(required = true, value = "Approval action that defines the behavior of the ItemApproval.")
  public ItemApprovalAction getApprovalAction() {
    return approvalAction;
  }

  public void setApprovalAction(ItemApprovalAction approvalAction) {
    this.approvalAction = approvalAction;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderItemApprovalRequest orderItemApprovalRequest = (OrderItemApprovalRequest) o;
    return Objects.equals(this.orderItemId, orderItemApprovalRequest.orderItemId) &&
        Objects.equals(this.approvalAction, orderItemApprovalRequest.approvalAction);
  }

  @Override
  public int hashCode() {
    return Objects.hash(orderItemId, approvalAction);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderItemApprovalRequest {\n");
    
    sb.append("    orderItemId: ").append(toIndentedString(orderItemId)).append("\n");
    sb.append("    approvalAction: ").append(toIndentedString(approvalAction)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

