/*
 * Selling Partner API for Retail Procurement Shipments
 * The Selling Partner API for Retail Procurement Shipments provides programmatic access to retail shipping data for vendors.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.amazon.spapi.model.vendor_shipments_api_model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Duration
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-05-03T19:54:08.878-04:00")
public class Duration {
  /**
   * Unit for duration.
   */
  @JsonAdapter(DurationUnitEnum.Adapter.class)
  public enum DurationUnitEnum {
    DAYS("Days"),
    
    MONTHS("Months");

    private String value;

    DurationUnitEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static DurationUnitEnum fromValue(String text) {
      for (DurationUnitEnum b : DurationUnitEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<DurationUnitEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final DurationUnitEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public DurationUnitEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return DurationUnitEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("durationUnit")
  private DurationUnitEnum durationUnit = null;

  @SerializedName("durationValue")
  private Integer durationValue = null;

  public Duration durationUnit(DurationUnitEnum durationUnit) {
    this.durationUnit = durationUnit;
    return this;
  }

   /**
   * Unit for duration.
   * @return durationUnit
  **/
  @ApiModelProperty(required = true, value = "Unit for duration.")
  public DurationUnitEnum getDurationUnit() {
    return durationUnit;
  }

  public void setDurationUnit(DurationUnitEnum durationUnit) {
    this.durationUnit = durationUnit;
  }

  public Duration durationValue(Integer durationValue) {
    this.durationValue = durationValue;
    return this;
  }

   /**
   * Value for the duration in terms of the durationUnit.
   * @return durationValue
  **/
  @ApiModelProperty(required = true, value = "Value for the duration in terms of the durationUnit.")
  public Integer getDurationValue() {
    return durationValue;
  }

  public void setDurationValue(Integer durationValue) {
    this.durationValue = durationValue;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Duration duration = (Duration) o;
    return Objects.equals(this.durationUnit, duration.durationUnit) &&
        Objects.equals(this.durationValue, duration.durationValue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(durationUnit, durationValue);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Duration {\n");
    
    sb.append("    durationUnit: ").append(toIndentedString(durationUnit)).append("\n");
    sb.append("    durationValue: ").append(toIndentedString(durationValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

