/*
 * Selling Partner API for Pricing
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer pricing information for Amazon Marketplace products.  For more information, see the [Product Pricing v2022-05-01 Use Case Guide](doc:product-pricing-api-v2022-05-01-use-case-guide).
 *
 * OpenAPI spec version: 2022-05-01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.amazon.spapi.model.product_pricing_api_model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The condition of the item.
 */
@JsonAdapter(Condition.Adapter.class)
public enum Condition {
  
  NEW("New"),
  
  USED("Used"),
  
  COLLECTIBLE("Collectible"),
  
  REFURBISHED("Refurbished"),
  
  CLUB("Club");

  private String value;

  Condition(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static Condition fromValue(String text) {
    for (Condition b : Condition.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<Condition> {
    @Override
    public void write(final JsonWriter jsonWriter, final Condition enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public Condition read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return Condition.fromValue(String.valueOf(value));
    }
  }
}

